### ISSUE TITLE
Access to $this and viewHelpers in .tpl file?

### ISSUE THREAD

**Issue by kozik** [skillfish/zf3-smarty-module#5]
Hi, I have problem. How access to `$this` variable in .tpl file?
In .phtml eg. `<?= $this->doctype() ?>` or `<?= $this->url('home') ?>` but how in .tpl?
`{$this->doctype()}` not working...
Best regards!

**Comment by psohm** [comment]
I have the same problem. did you resolve it ?

**Comment by kozik** [comment]
Unfortunately, I did not find a solution to my problem :-(

**Comment by psohm** [comment]
I found a system which was working but it was made for Smarty 3 + ZF2 
https://github.com/NikolayMurha/SmartyModule

below the result of my current work : 

1. all the problem seems to be issued from src/View/Renderer.php, we have to change the line 64
            if ($values instanceof ArrayObject) {
                $values = $values->getArrayCopy();
            **} else {
                $values = new ArrayObject();
            }
            $values['this'] = $this;**
if we make that change, $this is not null but there are some missing func like {$this->url}

1. in that case, we have inherit PhpRenderer and not implement
but i have now that error : 
[Wed Nov 28 14:01:20 2018] PHP Fatal error:  Uncaught Zend\View\Exception\RuntimeException: No RouteStackInterface instance provided in C:\Travail\Sogesa\PHP\gpmZF3\vendor\zendframework\zend-view\src\Helper\Url.php:60

**Comment by araeuchle** [comment]
Actually i found a solution to this problem, cuz i was bugging with it myself. 

In Renderer class under View you need to add several methods to get it working:


```
public function setHelperPluginManager($helper)
    {
        if (is_string($helper)) {
            if (! class_exists($helper)) {
                throw new InvalidArgumentException(sprintf(
                    'Invalid helper helpers class provided (%s)',
                    $helpers
                ));
            }
            $helper = new $helper(new ServiceManager());
        }
        if (! $helper instanceof HelperPluginManager) {
            throw new InvalidArgumentException(sprintf(
                'Helper helpers must extend Zend\View\HelperPluginManager; got type "%s" instead',
                (is_object($helper) ? get_class($helper) : gettype($helper))
            ));
        }
        $helper->setRenderer($this);
        $this->helper = $helper;

        return $this;
    }

    public function getHelperPluginManager()
    {
        if ($this->helper === null) {
            $this->setHelperPluginManager(new HelperPluginManager(new ServiceManager()));
        }

        return $this->helper;
    }

    public function plugin($name, array $options = null)
    {
        return $this->getHelperPluginManager()->get($name, $options);
    }

    public function __call($method, $argv)
    {
        $plugin = $this->plugin($method);

        if (is_callable($plugin)) {
            return call_user_func_array($plugin, $argv);
        }

        return $plugin;
    }
```

YOu also have to add a helper protected property in this class. 
I figured it out by digging through zf3s PHP Renderer class.

**Comment by skillfish** [comment]
Should be integrated with #6
